### ISSUE TITLE
9 / 5 

### ISSUE THREAD

**Issue by tallinn-learning** [RM-QA/homework-3#1]
https://github.com/RM-QA/homework-3/blob/1778d0fbd93ff7ca47659ea071978ace0993a1de/src/com/rehab/homeWork/Main.java#L25C3-L25C3

In Java, when you divide two integers like 9 / 5, the result is also an integer, which means it will truncate the decimal part, resulting in the value 1.

To fix this issue and perform accurate temperature conversion, you should use floating-point numbers in your division operation, like this:

double c = 26;    // Variable (c) means temperature in Celsius
double f = (9.0 / 5.0) * c + 32;
System.out.println(f);

**Comment by RM-QA** [comment]
thank you , done
