### ISSUE TITLE
The problem is with the expression (9 / 5) * c. In Java, when you divide two integers like 9 / 5, the result is also an integer

### ISSUE THREAD

**Issue by tallinn-learning** [RM-QA/homework-3#3]
https://github.com/RM-QA/homework-3/blob/1778d0fbd93ff7ca47659ea071978ace0993a1de/src/com/rehab/homeWork/Main.java#L25

double c = 26;    // Variable (c) means temperature in Celsius
double f = (9.0 / 5.0) * c + 32;
System.out.println(f);

**Comment by RM-QA** [comment]
thank you , done
