### ISSUE TITLE
 The variable names you've used in your code are generally acceptable and clear, but they could be improved for better readability.

### ISSUE THREAD

**Issue by tallinn-learning** [RM-QA/homework-3#4]
https://github.com/RM-QA/homework-3/blob/1778d0fbd93ff7ca47659ea071978ace0993a1de/src/com/rehab/homeWork/Main.java#L57C7-L63C31

**Comment by tallinn-learning** [comment]
int firstNumber = scanner.nextInt();
int secondNumber = scanner.nextInt();
int sum = firstNumber + secondNumber;

**Comment by RM-QA** [comment]
thank you , done
